### ISSUE TITLE
provide release libs to use them directly instead of Build by users

### ISSUE THREAD

**Issue by PramUkesh** [cginternals/cppfs#16]
provide release libs to use them directly instead of Build by users
so people can easily use them in their projects 
c make is not such popular for most of the people coming from other languages so its hard to build the libraries so provide release build on releases page so we can use them

**Comment by scheibel** [comment]
As this lib received some sort of popularity, we will provide  pre-built libraries shortly.

Do you have particular systems in mind?
By default, we try to target Windows (installer attached to releases), macOS (own homebrew tap), and Ubuntu (PPA).
Further, it seems like there are maintainers willing to provide packages of our software for Arch Linux, Debian, Homebrew and vcpkg.

**Comment by cgcostume** [comment]
The [cppfs-1.2.0](https://github.com/cginternals/cppfs/releases/tag/v1.2.0) release provides msvc 15 (2017) prebuild library and examples. We usually provide only prebuild packages for the latest msvc. 

@PramUkesh thanks for your feedback. Which platform are you talking about? Does the msvc prebuild solve this issue?

**Comment by PramUkesh** [comment]
for windows minGW 64 and 32

**Comment by scheibel** [comment]
Regarding MinGW, we depend on actual MinGW distribution maintainer to package for us.
We might change this in the future, but we currently have no build infrastructure running for this.
Closing for now.
