### ISSUE TITLE
File system watcher

### ISSUE THREAD

**Issue by scheibel** [cginternals/cppfs#3]
Moved from https://github.com/cginternals/cppassist/issues/4.

**Comment by robiwano** [comment]
Is there any work being done on this ? I'm in need of a simple filesystem watcher and could maybe contribute with at least linux + windows watchers.

**Comment by sbusch42** [comment]
Let's do it then :)

I've created a branch and starting implementing the linux backend:
  https://github.com/cginternals/cppfs/tree/watcher

You could start implementing the Windows backend, if you like.
Please comment on the architecture and design.

**Comment by robiwano** [comment]
Actually, I've already implemented the Windows parts, and have started on linux backend, I'll push to my own fork it you want to check it out.

**Comment by robiwano** [comment]
Since inotify isn't recursive, I need to add watches on subfolders, and handle creation of subfolders aswell. Please do have a view at https://github.com/robiwano/cppfs for the general design pattern for file watchers.

**Comment by robiwano** [comment]
branch is feature/filewatch

**Comment by sbusch42** [comment]
ok, I'll look into it and copy the recursive stuff for the linux backend. We should decide whether we want to have recursive as a flag or not. If you could prepare a pull request for the Windows backend following the interface in the watcher branch, that would be great. Let me know if you want changes to the structure/interfaces etc.

**Comment by robiwano** [comment]
I'll check the API in the watcher branch :)

**Comment by sbusch42** [comment]
Please let me know if you are preparing a pull request for this branch to implement the Windows backend.

**Comment by robiwano** [comment]
Just finished a version, but I won't be able to do the pull request until tomorrow :)

Sent from my Xperia™ by Sony smartphone


---- Stefan Buschmann wrote ----


Please let me know if you are preparing a pull request for this branch to implement the Windows backend.

**Comment by robiwano** [comment]
I have a question regarding blocking watch(): My usecase will be a plugin whos lifetime is totally controlled from the outside. The watch() method will be called within a separate thread, thus, when the plugin is destroyed, the watch() method must unblock in order to terminate the thread in an orderly fashion. Thoughts ?

**Comment by robiwano** [comment]
Maybe add a timeout option to watch ? So it can return after X milliseconds ?

**Comment by robiwano** [comment]
Ok, I'm going with the timeout parameter to watch, turns out to be to cleanest approach. Will also update the cppfs-watch example to take a time parameter so it exist the application after the given time.

**Comment by sbusch42** [comment]
I think having a timeout parameter would be a good solution. Please make it optional, so by default it should block without timeout. Maybe this helps for the posix implementation:
  https://stackoverflow.com/questions/2917881/how-to-implement-a-timeout-in-read-function-call

**Comment by robiwano** [comment]
Yes, I found that same exact post :), seems to work fine for posix implementation, now I just need to get my VS IDE up and running (license expired 😏 )...

**Comment by robiwano** [comment]
Btw, is it possible via cppassist cmd line tools to get multiple unnamed parameters into a vector of strings ? I'd like to be able to set multiple paths to monitor in cppfs-watch.

**Comment by robiwano** [comment]
Pull request issued.

**Comment by sbusch42** [comment]
This has finally been merged. Thank you very much for your contribution!
Please let me know if there are any more issues with this, or if I accidentally broke something with my latest changes :)
