### ISSUE TITLE
Watching files doesn't work on windows?

### ISSUE THREAD

**Issue by xahon** [cginternals/cppfs#33]
```C++
class TestFileEventHandler : public FileEventHandler {
   public:
    virtual void onFileEvent(FileHandle& fh, FileEvent event) override { //
        LOG_DEBUG("File Event"); // Not getting called
    }
};

int main() {
    TestFileEventHandler eventHandler;
    FileWatcher watcher;
    FileHandle dir = Fs::OpenFileHandle(std::move(std::string("assets://shaders")));
    // Valid path. Expands to "C:/dev/opengl_game/out/build/x64-Debug/bin/assets/shaders"
    watcher.add(dir);
    watcher.addHandler(&eventHandler);

    while (true) {
        watcher.watch(-1);
        LOG_DEBUG("Loop");
    }

    return 0;
}
```

**Comment by sbusch42** [comment]
Unfortunately, I don't have a Windows system to test this at the moment.
- Have you tested this on a different path ("C:\..."), does it work there? (so it has something to do with the "assets://" path?)
- Can you confirm that a valid instance of LocalFileWatcher backend is created?

I'm not aware of this "assets://" path and I don't find anything about it. I doubt this is a valid Windows path. How does this work and what system is responsible for expanding it? How is it expanded to "C:/dev/opengl_game"?

**Comment by xahon** [comment]
@sbusch42  Sorry, my bad. I opened file watcher in binary path and tried to change sources in source directory

P.S. `Fs::OpenFileHandle` does this path convertion under the hood - it is my custom command that points to the binary_dir/assets/shaders
