### ISSUE TITLE
removeDirectoryRec recursively follows symlink directories and should not ?

### ISSUE THREAD

**Issue by gst** [cginternals/cppfs#39]
Hi,

it looks like removeDirectoryRec follow/enter directories symlinks.. which I think should better not be by default.

the issue is that there is no option to not follow/enter directories symlink.

Could we foresee to have/add such an option flag/bool to the function signature ?

I would be happy to contribute if that would be agreed

```c++
-void removeDirectoryRec() {
+void removeDirectoryRec(bool followSymlinks=false) {

...

        if (fh.isDirectory())
        {
+          if(fh.isSymbolicLink() && !followSymlinks)
+             fh.remove();
+          else
                fh.removeDirectoryRec();
        }
```

**Comment by sbusch42** [comment]
Looks good to me. If you create a PR, I will merge it in.

**Comment by gst** [comment]
ok I will do that ASAP then, thanks for the answer :)

**Comment by gst** [comment]
here it is : https://github.com/cginternals/cppfs/pull/40

**Comment by scheibel** [comment]
Seems like we can close this issue. Thanks for contributing!
