### ISSUE TITLE
Error in testing (googletest)

### ISSUE THREAD

**Issue by itzAnasov** [cginternals/cppfs#41]
```shell
...
[ 72%] Building CXX object source/tests/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /opt/Development/libs/cppfs/source/tests/googletest/googletest/src/gtest-all.cc:42:
/opt/Development/libs/cppfs/source/tests/googletest/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
/opt/Development/libs/cppfs/source/tests/googletest/googletest/src/gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
 1301 |   StackLowerThanAddress(&dummy, &result);
...
```

i've got this error in both of my **linux** devices [Arch/Debian].
The way I used to get around the problem was to stop all tests by typing `cmake .. -DOPTION_BUILD_TESTS=OFF`, and I was able to build and install the library

**Comment by scheibel** [comment]
Thanks for reporting.
We're experiencing recurring problems with our in-source `googletest` module.
I updated the cppfs repository to reflect our more robust use of an external `googletest` installation.
